//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.InteropServices;

namespace FS.MQ.RocketMQ.SDK
{
    public class LocalTransactionChecker : IDisposable
    {
        public delegate int SwigDelegateLocalTransactionChecker_0(IntPtr msg);

        private static readonly Type[] swigMethodTypes0 = {typeof(Message)};
        protected bool swigCMemOwn;
        private HandleRef swigCPtr;

        private SwigDelegateLocalTransactionChecker_0 swigDelegate0;

        internal LocalTransactionChecker(IntPtr cPtr, bool cMemoryOwn)
        {
            swigCMemOwn = cMemoryOwn;
            swigCPtr = new HandleRef(this, cPtr);
        }

        public LocalTransactionChecker() : this(ONSClient4CPPPINVOKE.new_LocalTransactionChecker(), true)
        {
            SwigDirectorConnect();
        }

        public virtual void Dispose()
        {
            lock (this)
            {
                if (swigCPtr.Handle != IntPtr.Zero)
                {
                    if (swigCMemOwn)
                    {
                        swigCMemOwn = false;
                        ONSClient4CPPPINVOKE.delete_LocalTransactionChecker(swigCPtr);
                    }
                    swigCPtr = new HandleRef(null, IntPtr.Zero);
                }
                GC.SuppressFinalize(this);
            }
        }

        internal static HandleRef getCPtr(LocalTransactionChecker obj)
        {
            return obj == null ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
        }

        ~LocalTransactionChecker()
        {
            Dispose();
        }

        public virtual TransactionStatus check(Message msg)
        {
            var ret = (TransactionStatus) ONSClient4CPPPINVOKE.LocalTransactionChecker_check(swigCPtr,
                Message.getCPtr(msg));
            if (ONSClient4CPPPINVOKE.SWIGPendingException.Pending)
                throw ONSClient4CPPPINVOKE.SWIGPendingException.Retrieve();
            return ret;
        }

        private void SwigDirectorConnect()
        {
            if (SwigDerivedClassHasMethod("check", swigMethodTypes0))
                swigDelegate0 = SwigDirectorcheck;
            ONSClient4CPPPINVOKE.LocalTransactionChecker_director_connect(swigCPtr, swigDelegate0);
        }

        private bool SwigDerivedClassHasMethod(string methodName, Type[] methodTypes)
        {
            var methodInfo = GetType().GetMethod(methodName,
                BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance, null, methodTypes, null);
            var hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(LocalTransactionChecker));
            return hasDerivedMethod;
        }

        private int SwigDirectorcheck(IntPtr msg)
        {
            return (int) check(new Message(msg, false));
        }
    }
}