//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


#pragma warning disable 1591

namespace FS.MQ.RocketMQ.SDK
{
    public enum Action
    {
        /// <summary>
        ///     确认消费
        /// </summary>
        CommitMessage,
        /// <summary>
        ///     过后重试
        /// </summary>
        ReconsumeLater
    }
}