//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Farseer.Net.MQ.RocketMQ.SDK
{
    public enum ONSPullStatus
    {
        ONS_FOUND,
        ONS_NO_NEW_MSG,
        ONS_NO_MATCHED_MSG,
        ONS_OFFSET_ILLEGAL,
        ONS_BROKER_TIMEOUT
    }
}