//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

using System;
using System.Runtime.InteropServices;

namespace FS.MQ.RocketMQ.SDK
{
    public class TransactionProducer : IDisposable
    {
        protected bool swigCMemOwn;
        private HandleRef swigCPtr;

        internal TransactionProducer(IntPtr cPtr, bool cMemoryOwn)
        {
            swigCMemOwn = cMemoryOwn;
            swigCPtr = new HandleRef(this, cPtr);
        }

        public virtual void Dispose()
        {
            lock (this)
            {
                if (swigCPtr.Handle != IntPtr.Zero)
                {
                    if (swigCMemOwn)
                    {
                        swigCMemOwn = false;
                        ONSClient4CPPPINVOKE.delete_TransactionProducer(swigCPtr);
                    }
                    swigCPtr = new HandleRef(null, IntPtr.Zero);
                }
                GC.SuppressFinalize(this);
            }
        }

        internal static HandleRef getCPtr(TransactionProducer obj)
        {
            return obj == null ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
        }

        ~TransactionProducer()
        {
            Dispose();
        }

        public virtual void start()
        {
            ONSClient4CPPPINVOKE.TransactionProducer_start(swigCPtr);
        }

        public virtual void shutdown()
        {
            ONSClient4CPPPINVOKE.TransactionProducer_shutdown(swigCPtr);
        }

        public virtual SendResultONS send(Message msg, LocalTransactionExecuter executer)
        {
            var ret = new SendResultONS(
                ONSClient4CPPPINVOKE.TransactionProducer_send(swigCPtr, Message.getCPtr(msg),
                    LocalTransactionExecuter.getCPtr(executer)), true);
            if (ONSClient4CPPPINVOKE.SWIGPendingException.Pending)
                throw ONSClient4CPPPINVOKE.SWIGPendingException.Retrieve();
            return ret;
        }
    }
}